version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\parallel
image:
- Visual Studio 2013
configuration:
- Release
platform:
- x64
environment:
  access_token:
    secure: A9uxnM8l+sPtDq+VCfp+VQ==
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir _build
    cd _build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\parallel\_build\Project.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - main.cxx
on_success:
  - ps: |
      Set-Location \
      git clone -q --branch=master https://github.com/i-RIC/online_update.git
      Set-Location .\online_update
      git checkout -qf master
      $v=(Select-String -Path dev_src\packages\gui.prepost\meta\package.xml -Pattern "(?<=<Version>)(.*)(?=</Version>)").Matches.Value -split "\."
      $v[2] = 1 + $v[2]
      $Env:VERSION = $v -join "."
      $Env:RELEASE_DATE = $(Get-Date -Format o).Substring(0,10)
      $Env:RELEASE = $Env:RELEASE_DATE -replace '-', '.'
      $Env:CAPTION = "iRIC GUI " + $v[0] + "." + $v[1] + "." + $v[2]
      $files=@('dev_src\packages\gui.prepost\data\definition.xml', `
               'dev_src\packages\gui.prepost\meta\package.xml')
      foreach ($file in $files) {
        (Get-Content $file) | Foreach-Object {
          $_ -replace "(?<=<Version>)(.*)(?=</Version>)",           "$Env:VERSION" `
             -replace "`" version=`"([^`"]*)`"",                    "`" version=`"$Env:VERSION`"" `
             -replace "(?<=<ReleaseDate>)(.*)(?=</ReleaseDate>)",   "$Env:RELEASE_DATE" `
             -replace "release=`"([^`"]*)`"",                       "release=`"$Env:RELEASE`"" `
             -replace "caption=`"([^`"]*)`"",                       "caption=`"$Env:CAPTION`"" `
             -replace "github-sha1=`"([^`"]*)`"",                   "github-sha1=`"$Env:APPVEYOR_REPO_COMMIT`""
        } | Set-Content $file
      }
      git diff
